name: CI

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]
  release:
    types: [ 'created' ]

permissions:
  contents: read

env:
  # Use invalid OSB key to packages with ZIP support but without valid build in password
  OSB_KEY: "invalid"
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
  linuxbuild:
    name: Create Linux Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - run: make linux-package
      - name: Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *linux.tar.gz
  windowsbuild:
    name: Create Windows Package
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - run: make win-package
      - name: Release
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *win64.zip